# For reference see https://www.gitpod.io/docs/references/gitpod-yml
image: gitpod/workspace-postgres

tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      echo "🚀 Starting Server..."
      npm run dev
      echo "🎉 Server Started!"

ports:
  - port: 3000
    onOpen: open-browser
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
  - svelte.svelte-vscode
  - zhuangtongfa.material-theme

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true