---
# For reference see https://www.gitpod.io/docs/references/gitpod-yml
image: gitpod/workspace-postgres

tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      echo "🚀 Starting Server..."
      npm run dev
      echo "🎉 Server Started!"
    env:
      DATABASE_URL: postgres://gitpod@localhost/todos
  - command: |
      npx prisma studio 
    env:
      DATABASE_URL: postgres://gitpod@localhost/todos

ports:
  - port: 3000
    onOpen: open-browser
  - port: 5432
    onOpen: ignore
  - port: 5555
    onOpen: open-browser

vscode:
  extensions:
  - svelte.svelte-vscode
  - zhuangtongfa.material-theme
  - prisma.prisma

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
