tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      echo "🚀 Starting Server..."
      npm run dev
      echo "🎉 Server Started!"

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
  - svelte.svelte-vscode
  - zhuangtongfa.material-theme
